// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	ContentType          []byte   `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	CompressingMode      uint32   `protobuf:"varint,2,opt,name=compressing_mode,json=compressingMode,proto3" json:"compressing_mode,omitempty"`
	Length               uint32   `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	Target               []byte   `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	ServiceName          []byte   `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Method               []byte   `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetContentType() []byte {
	if m != nil {
		return m.ContentType
	}
	return nil
}

func (m *Request) GetCompressingMode() uint32 {
	if m != nil {
		return m.CompressingMode
	}
	return 0
}

func (m *Request) GetLength() uint32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *Request) GetTarget() []byte {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *Request) GetServiceName() []byte {
	if m != nil {
		return m.ServiceName
	}
	return nil
}

func (m *Request) GetMethod() []byte {
	if m != nil {
		return m.Method
	}
	return nil
}

type Response struct {
	ContentType          []byte   `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	CompressingMode      uint32   `protobuf:"varint,2,opt,name=compressing_mode,json=compressingMode,proto3" json:"compressing_mode,omitempty"`
	Length               []byte   `protobuf:"bytes,3,opt,name=length,proto3" json:"length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetContentType() []byte {
	if m != nil {
		return m.ContentType
	}
	return nil
}

func (m *Response) GetCompressingMode() uint32 {
	if m != nil {
		return m.CompressingMode
	}
	return 0
}

func (m *Response) GetLength() []byte {
	if m != nil {
		return m.Length
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "protocol.Request")
	proto.RegisterType((*Response)(nil), "protocol.Response")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x90, 0xbd, 0x4e, 0xc4, 0x30,
	0x10, 0x84, 0x15, 0x7e, 0xc2, 0x61, 0x82, 0x40, 0x29, 0x90, 0xcb, 0xe3, 0x10, 0xd2, 0xd1, 0x5c,
	0x0a, 0xde, 0x80, 0x1e, 0x8a, 0x88, 0x8a, 0x26, 0x4a, 0x9c, 0x91, 0x13, 0x14, 0x7b, 0x8d, 0xbd,
	0x41, 0xba, 0xd7, 0xe3, 0xc9, 0xd0, 0x39, 0x3e, 0x89, 0x17, 0xa0, 0xb2, 0xe7, 0xd3, 0xee, 0x8c,
	0x66, 0xc5, 0xa5, 0x09, 0x7a, 0xe7, 0x3c, 0x31, 0x95, 0xab, 0xf8, 0x28, 0x9a, 0x36, 0x3f, 0x99,
	0xb8, 0xa8, 0xf1, 0x35, 0x23, 0x70, 0x79, 0x2f, 0x0a, 0x45, 0x96, 0x61, 0xb9, 0xe1, 0xbd, 0x83,
	0xcc, 0xd6, 0xd9, 0xb6, 0xa8, 0xaf, 0x12, 0x7b, 0xdf, 0x3b, 0x94, 0x4f, 0xe2, 0x56, 0x91, 0x71,
	0x1e, 0x21, 0x8c, 0x56, 0x37, 0x86, 0x7a, 0xc8, 0x93, 0x75, 0xb6, 0xbd, 0xae, 0x6f, 0xfe, 0xf0,
	0x57, 0xea, 0x51, 0xde, 0x89, 0x7c, 0x82, 0xd5, 0x3c, 0xc8, 0xd3, 0x38, 0x90, 0xd4, 0x81, 0x73,
	0xeb, 0x35, 0x58, 0x9e, 0x45, 0xff, 0xa4, 0x0e, 0xe9, 0x01, 0xfe, 0x7b, 0x54, 0x68, 0x6c, 0x6b,
	0x20, 0xcf, 0x97, 0xf4, 0xc4, 0xde, 0x5a, 0x13, 0x2d, 0x0d, 0x78, 0xa0, 0x5e, 0xe6, 0xcb, 0xea,
	0xa2, 0x36, 0x4e, 0xac, 0x6a, 0x04, 0x47, 0x36, 0xe0, 0x5f, 0x4b, 0x14, 0xc7, 0x12, 0x2f, 0x8f,
	0x1f, 0x0f, 0x7a, 0xe4, 0x61, 0xee, 0x76, 0x8a, 0x4c, 0x35, 0xcd, 0x5d, 0x6b, 0x9d, 0xa7, 0xcf,
	0x4a, 0x93, 0x77, 0xaa, 0x3a, 0x5e, 0xb7, 0xcb, 0xe3, 0xef, 0xf9, 0x37, 0x00, 0x00, 0xff, 0xff,
	0x0c, 0x05, 0x32, 0xea, 0x7b, 0x01, 0x00, 0x00,
}
